
name: Manual Pyinstaller

# Builds using Pyinstaller

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      pyfile:
        description: 'Target Python File'
        required: true
        type: string
      pip-install:
        description: 'Modules to install'
        required: true
        type: string

jobs:
  pyinstaller-build:
    runs-on: windows-latest #ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          #pyinstaller_ver: '==5.13.2'
          #spec: 'src/build.spec'
          #requirements: 'src/requirements.txt'
          #upload_exe_with_name: 'My executable'
          options: --onefile, --windowed  # --name "My App",
          #spec_options: # any custom arguments you want like: `--debug`

  
       #run: echo "Hello ${{ inputs.name }}"
