
name: Manual Pyinstaller

# Builds using Pyinstaller

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      pyfile:
        description: 'Target Python File'
        required: true
        type: string
      pip-install:
        description: 'Modules to install'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
       #run: echo "Hello ${{ inputs.name }}"
